/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    positions: Position;
    locations: Location;
    categories: Category;
    news: News;
    events: Event;
    brands: Brand;
    menus: Menu;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    positions: PositionsSelect<false> | PositionsSelect<true>;
    locations: LocationsSelect<false> | LocationsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    brands: BrandsSelect<false> | BrandsSelect<true>;
    menus: MenusSelect<false> | MenusSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    'site-configuration': SiteConfiguration;
  };
  globalsSelect: {
    'site-configuration': SiteConfigurationSelect<false> | SiteConfigurationSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  avatar?: (number | null) | Media;
  roles?: ('admin' | 'webAdmin' | 'editor' | 'user')[] | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug?: string | null;
  description: string;
  startDateTime?: string | null;
  endDateTime?: string | null;
  menu?: (number | null) | Menu;
  status: 'draft' | 'request-review' | 'on-review' | 'publish' | 'unpublish' | 'schedule';
  content?:
    | (
        | {
            headline: string;
            tagline: string;
            asset: {
              type: 'image' | 'video' | 'color';
              media?: (number | null) | Media;
              color?: string | null;
            };
            assetPosition: 'left' | 'right';
            description: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            descriptionShort: string;
            brands?: (number | Brand)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'twoColumns';
          }
        | {
            title: string;
            description: string;
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            background: {
              position: 'top-left' | 'top-right' | 'down-left' | 'down-right';
              image: number | Media;
            };
            ourLocationsType?: ('none' | 'single' | 'multiple') | null;
            singleLocation?: {
              location: {
                address: string;
                mapsUrl: string;
              };
              contact: {
                name: string;
                phoneNumber: string;
              };
              openHours?:
                | {
                    days: string;
                    hours: string;
                    id?: string | null;
                  }[]
                | null;
            };
            multipleLocation?:
              | {
                  address: string;
                  mapsUrl: string;
                  openHours: string;
                  contact: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            logo: number | Media;
            smallTitle: string;
            bigTitle: string;
            description: string;
            background: {
              type: 'image' | 'video' | 'color';
              media?: (number | null) | Media;
              color?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'heroFullscreen';
          }
        | {
            title: string;
            description: string;
            background?: (number | null) | Media;
            items: {
              title: string;
              appendTitle?: string | null;
              description: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'milestone';
          }
        | {
            type: 'dark' | 'light' | 'auto';
            title: string;
            description: string;
            images: {
              image: number | Media;
              id?: string | null;
            }[];
            style?: ('grid' | 'carousel' | 'masonry') | null;
            actions?:
              | {
                  label: string;
                  url: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
        | {
            title: string;
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            headline: string;
            tagline: string;
            collection: 'pages' | 'news' | 'events' | 'brands';
            relation?:
              | (
                  | {
                      relationTo: 'pages';
                      value: number | Page;
                    }
                  | {
                      relationTo: 'news';
                      value: number | News;
                    }
                  | {
                      relationTo: 'events';
                      value: number | Event;
                    }
                  | {
                      relationTo: 'brands';
                      value: number | Brand;
                    }
                )[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'carousel';
          }
        | {
            title: string;
            description: string;
            collection: 'pages' | 'news' | 'events' | 'brands';
            itemType: 'one' | 'two' | 'three' | 'four' | 'five' | 'six' | 'seven';
            items?:
              | (
                  | {
                      relationTo: 'pages';
                      value: number | Page;
                    }
                  | {
                      relationTo: 'news';
                      value: number | News;
                    }
                  | {
                      relationTo: 'events';
                      value: number | Event;
                    }
                  | {
                      relationTo: 'brands';
                      value: number | Brand;
                    }
                )[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'slider';
          }
        | {
            icon: number | Media;
            platform: string;
            url: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
      )[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    canonicalUrl?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menus".
 */
export interface Menu {
  id: number;
  title: string;
  parent?: (number | null) | Menu;
  path?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands".
 */
export interface Brand {
  id: number;
  name: string;
  description: string;
  menu?: (number | null) | Menu;
  category?: (number | null) | Category;
  logo?: (number | null) | Media;
  blocks?:
    | (
        | {
            title: string;
            description: string;
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            background: {
              position: 'top-left' | 'top-right' | 'down-left' | 'down-right';
              image: number | Media;
            };
            ourLocationsType?: ('none' | 'single' | 'multiple') | null;
            singleLocation?: {
              location: {
                address: string;
                mapsUrl: string;
              };
              contact: {
                name: string;
                phoneNumber: string;
              };
              openHours?:
                | {
                    days: string;
                    hours: string;
                    id?: string | null;
                  }[]
                | null;
            };
            multipleLocation?:
              | {
                  address: string;
                  mapsUrl: string;
                  openHours: string;
                  contact: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            type: 'dark' | 'light' | 'auto';
            title: string;
            description: string;
            images: {
              image: number | Media;
              id?: string | null;
            }[];
            style?: ('grid' | 'carousel' | 'masonry') | null;
            actions?:
              | {
                  label: string;
                  url: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
        | {
            title: string;
            description: string;
            collection: 'pages' | 'news' | 'events' | 'brands';
            itemType: 'one' | 'two' | 'three' | 'four' | 'five' | 'six' | 'seven';
            items?:
              | (
                  | {
                      relationTo: 'pages';
                      value: number | Page;
                    }
                  | {
                      relationTo: 'news';
                      value: number | News;
                    }
                  | {
                      relationTo: 'events';
                      value: number | Event;
                    }
                  | {
                      relationTo: 'brands';
                      value: number | Brand;
                    }
                )[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'slider';
          }
        | {
            title: string;
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
      )[]
    | null;
  locations?:
    | {
        address: string;
        mapsUrl: string;
        openHours?:
          | {
              title: string;
              description: string;
              id?: string | null;
            }[]
          | null;
        contact?:
          | {
              type: string;
              value: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  status: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  description?: string | null;
  group?: ('brands' | 'events') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  headline: string;
  tagline?: string | null;
  image?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  active: boolean;
  categories?: (number | Category)[] | null;
  menu?: (number | null) | Menu;
  blocks?:
    | (
        | {
            title: string;
            description: string;
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            background: {
              position: 'top-left' | 'top-right' | 'down-left' | 'down-right';
              image: number | Media;
            };
            ourLocationsType?: ('none' | 'single' | 'multiple') | null;
            singleLocation?: {
              location: {
                address: string;
                mapsUrl: string;
              };
              contact: {
                name: string;
                phoneNumber: string;
              };
              openHours?:
                | {
                    days: string;
                    hours: string;
                    id?: string | null;
                  }[]
                | null;
            };
            multipleLocation?:
              | {
                  address: string;
                  mapsUrl: string;
                  openHours: string;
                  contact: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            type: 'dark' | 'light' | 'auto';
            title: string;
            description: string;
            images: {
              image: number | Media;
              id?: string | null;
            }[];
            style?: ('grid' | 'carousel' | 'masonry') | null;
            actions?:
              | {
                  label: string;
                  url: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
        | {
            title: string;
            description: string;
            collection: 'pages' | 'news' | 'events' | 'brands';
            itemType: 'one' | 'two' | 'three' | 'four' | 'five' | 'six' | 'seven';
            items?:
              | (
                  | {
                      relationTo: 'pages';
                      value: number | Page;
                    }
                  | {
                      relationTo: 'news';
                      value: number | News;
                    }
                  | {
                      relationTo: 'events';
                      value: number | Event;
                    }
                  | {
                      relationTo: 'brands';
                      value: number | Brand;
                    }
                )[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'slider';
          }
        | {
            title: string;
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  headline: string;
  tagline?: string | null;
  image?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  startDate: string;
  endDate: string;
  active: boolean;
  menu?: (number | null) | Menu;
  blocks?:
    | (
        | {
            title: string;
            description: string;
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            background: {
              position: 'top-left' | 'top-right' | 'down-left' | 'down-right';
              image: number | Media;
            };
            ourLocationsType?: ('none' | 'single' | 'multiple') | null;
            singleLocation?: {
              location: {
                address: string;
                mapsUrl: string;
              };
              contact: {
                name: string;
                phoneNumber: string;
              };
              openHours?:
                | {
                    days: string;
                    hours: string;
                    id?: string | null;
                  }[]
                | null;
            };
            multipleLocation?:
              | {
                  address: string;
                  mapsUrl: string;
                  openHours: string;
                  contact: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            type: 'dark' | 'light' | 'auto';
            title: string;
            description: string;
            images: {
              image: number | Media;
              id?: string | null;
            }[];
            style?: ('grid' | 'carousel' | 'masonry') | null;
            actions?:
              | {
                  label: string;
                  url: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
        | {
            title: string;
            description: string;
            collection: 'pages' | 'news' | 'events' | 'brands';
            itemType: 'one' | 'two' | 'three' | 'four' | 'five' | 'six' | 'seven';
            items?:
              | (
                  | {
                      relationTo: 'pages';
                      value: number | Page;
                    }
                  | {
                      relationTo: 'news';
                      value: number | News;
                    }
                  | {
                      relationTo: 'events';
                      value: number | Event;
                    }
                  | {
                      relationTo: 'brands';
                      value: number | Brand;
                    }
                )[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'slider';
          }
        | {
            title: string;
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "positions".
 */
export interface Position {
  id: number;
  name: string;
  description: string;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations".
 */
export interface Location {
  id: number;
  name: string;
  description: string;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'positions';
        value: number | Position;
      } | null)
    | ({
        relationTo: 'locations';
        value: number | Location;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'brands';
        value: number | Brand;
      } | null)
    | ({
        relationTo: 'menus';
        value: number | Menu;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  avatar?: T;
  roles?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  startDateTime?: T;
  endDateTime?: T;
  menu?: T;
  status?: T;
  content?:
    | T
    | {
        twoColumns?:
          | T
          | {
              headline?: T;
              tagline?: T;
              asset?:
                | T
                | {
                    type?: T;
                    media?: T;
                    color?: T;
                  };
              assetPosition?: T;
              description?: T;
              descriptionShort?: T;
              brands?: T;
              id?: T;
              blockName?: T;
            };
        hero?:
          | T
          | {
              title?: T;
              description?: T;
              content?: T;
              background?:
                | T
                | {
                    position?: T;
                    image?: T;
                  };
              ourLocationsType?: T;
              singleLocation?:
                | T
                | {
                    location?:
                      | T
                      | {
                          address?: T;
                          mapsUrl?: T;
                        };
                    contact?:
                      | T
                      | {
                          name?: T;
                          phoneNumber?: T;
                        };
                    openHours?:
                      | T
                      | {
                          days?: T;
                          hours?: T;
                          id?: T;
                        };
                  };
              multipleLocation?:
                | T
                | {
                    address?: T;
                    mapsUrl?: T;
                    openHours?: T;
                    contact?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        heroFullscreen?:
          | T
          | {
              logo?: T;
              smallTitle?: T;
              bigTitle?: T;
              description?: T;
              background?:
                | T
                | {
                    type?: T;
                    media?: T;
                    color?: T;
                  };
              id?: T;
              blockName?: T;
            };
        milestone?:
          | T
          | {
              title?: T;
              description?: T;
              background?: T;
              items?:
                | T
                | {
                    title?: T;
                    appendTitle?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              type?: T;
              title?: T;
              description?: T;
              images?:
                | T
                | {
                    image?: T;
                    id?: T;
                  };
              style?: T;
              actions?:
                | T
                | {
                    label?: T;
                    url?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              title?: T;
              content?: T;
              id?: T;
              blockName?: T;
            };
        carousel?:
          | T
          | {
              headline?: T;
              tagline?: T;
              collection?: T;
              relation?: T;
              id?: T;
              blockName?: T;
            };
        slider?:
          | T
          | {
              title?: T;
              description?: T;
              collection?: T;
              itemType?: T;
              items?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              icon?: T;
              platform?: T;
              url?: T;
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonicalUrl?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "positions_select".
 */
export interface PositionsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations_select".
 */
export interface LocationsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  group?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  headline?: T;
  tagline?: T;
  image?: T;
  content?: T;
  active?: T;
  categories?: T;
  menu?: T;
  blocks?:
    | T
    | {
        hero?:
          | T
          | {
              title?: T;
              description?: T;
              content?: T;
              background?:
                | T
                | {
                    position?: T;
                    image?: T;
                  };
              ourLocationsType?: T;
              singleLocation?:
                | T
                | {
                    location?:
                      | T
                      | {
                          address?: T;
                          mapsUrl?: T;
                        };
                    contact?:
                      | T
                      | {
                          name?: T;
                          phoneNumber?: T;
                        };
                    openHours?:
                      | T
                      | {
                          days?: T;
                          hours?: T;
                          id?: T;
                        };
                  };
              multipleLocation?:
                | T
                | {
                    address?: T;
                    mapsUrl?: T;
                    openHours?: T;
                    contact?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              type?: T;
              title?: T;
              description?: T;
              images?:
                | T
                | {
                    image?: T;
                    id?: T;
                  };
              style?: T;
              actions?:
                | T
                | {
                    label?: T;
                    url?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        slider?:
          | T
          | {
              title?: T;
              description?: T;
              collection?: T;
              itemType?: T;
              items?: T;
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              title?: T;
              content?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  headline?: T;
  tagline?: T;
  image?: T;
  content?: T;
  startDate?: T;
  endDate?: T;
  active?: T;
  menu?: T;
  blocks?:
    | T
    | {
        hero?:
          | T
          | {
              title?: T;
              description?: T;
              content?: T;
              background?:
                | T
                | {
                    position?: T;
                    image?: T;
                  };
              ourLocationsType?: T;
              singleLocation?:
                | T
                | {
                    location?:
                      | T
                      | {
                          address?: T;
                          mapsUrl?: T;
                        };
                    contact?:
                      | T
                      | {
                          name?: T;
                          phoneNumber?: T;
                        };
                    openHours?:
                      | T
                      | {
                          days?: T;
                          hours?: T;
                          id?: T;
                        };
                  };
              multipleLocation?:
                | T
                | {
                    address?: T;
                    mapsUrl?: T;
                    openHours?: T;
                    contact?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              type?: T;
              title?: T;
              description?: T;
              images?:
                | T
                | {
                    image?: T;
                    id?: T;
                  };
              style?: T;
              actions?:
                | T
                | {
                    label?: T;
                    url?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        slider?:
          | T
          | {
              title?: T;
              description?: T;
              collection?: T;
              itemType?: T;
              items?: T;
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              title?: T;
              content?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands_select".
 */
export interface BrandsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  menu?: T;
  category?: T;
  logo?: T;
  blocks?:
    | T
    | {
        hero?:
          | T
          | {
              title?: T;
              description?: T;
              content?: T;
              background?:
                | T
                | {
                    position?: T;
                    image?: T;
                  };
              ourLocationsType?: T;
              singleLocation?:
                | T
                | {
                    location?:
                      | T
                      | {
                          address?: T;
                          mapsUrl?: T;
                        };
                    contact?:
                      | T
                      | {
                          name?: T;
                          phoneNumber?: T;
                        };
                    openHours?:
                      | T
                      | {
                          days?: T;
                          hours?: T;
                          id?: T;
                        };
                  };
              multipleLocation?:
                | T
                | {
                    address?: T;
                    mapsUrl?: T;
                    openHours?: T;
                    contact?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              type?: T;
              title?: T;
              description?: T;
              images?:
                | T
                | {
                    image?: T;
                    id?: T;
                  };
              style?: T;
              actions?:
                | T
                | {
                    label?: T;
                    url?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        slider?:
          | T
          | {
              title?: T;
              description?: T;
              collection?: T;
              itemType?: T;
              items?: T;
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              title?: T;
              content?: T;
              id?: T;
              blockName?: T;
            };
      };
  locations?:
    | T
    | {
        address?: T;
        mapsUrl?: T;
        openHours?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
        contact?:
          | T
          | {
              type?: T;
              value?: T;
              id?: T;
            };
        id?: T;
      };
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menus_select".
 */
export interface MenusSelect<T extends boolean = true> {
  title?: T;
  parent?: T;
  path?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-configuration".
 */
export interface SiteConfiguration {
  id: number;
  logo: number | Media;
  favicon: number | Media;
  siteName: string;
  baseUrl: string;
  headline: string;
  tagline: string;
  primary_color?: string | null;
  secondary_color?: string | null;
  success_color?: string | null;
  warning_color?: string | null;
  danger_color?: string | null;
  info_color?: string | null;
  header: {
    logo: number | Media;
    menus: (number | Menu)[];
    button: {
      text: string;
      link: string;
    };
  };
  footer: {
    left: {
      logo: number | Media;
      text: string;
      socialMedia?:
        | {
            platform: string;
            icon: number | Media;
            url: string;
            id?: string | null;
          }[]
        | null;
    };
    right: {
      title: string;
      subtitle: string;
      mapUrl: string;
    };
    bottom: {
      copyright: string;
      reserve: string;
    };
  };
  title?: string | null;
  description?: string | null;
  /**
   * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
   */
  image?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-configuration_select".
 */
export interface SiteConfigurationSelect<T extends boolean = true> {
  logo?: T;
  favicon?: T;
  siteName?: T;
  baseUrl?: T;
  headline?: T;
  tagline?: T;
  primary_color?: T;
  secondary_color?: T;
  success_color?: T;
  warning_color?: T;
  danger_color?: T;
  info_color?: T;
  header?:
    | T
    | {
        logo?: T;
        menus?: T;
        button?:
          | T
          | {
              text?: T;
              link?: T;
            };
      };
  footer?:
    | T
    | {
        left?:
          | T
          | {
              logo?: T;
              text?: T;
              socialMedia?:
                | T
                | {
                    platform?: T;
                    icon?: T;
                    url?: T;
                    id?: T;
                  };
            };
        right?:
          | T
          | {
              title?: T;
              subtitle?: T;
              mapUrl?: T;
            };
        bottom?:
          | T
          | {
              copyright?: T;
              reserve?: T;
            };
      };
  title?: T;
  description?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}